brendandeere/solidus_subscriptions

- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/installment_detail.rb
- app/models/solidus_subscriptions/line_item.rb
- app/models/solidus_subscriptions/subscription.rb
- bin/console
- db/migrate/20160825164850_create_solidus_subscriptions_subscriptions.rb
- db/migrate/20160825173548_create_solidus_subscriptions_line_items.rb
- db/migrate/20160825202248_create_solidus_subscriptions_installments.rb
- db/migrate/20160825211202_create_solidus_subscriptions_installment_details.rb
- db/migrate/20160825214240_add_subscribable_to_spree_variants.rb
- lib/solidus_subscriptions/engine.rb
- solidus_subscriptions.gemspec
- spec/models/solidus_subscriptions/installment_detail_spec.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Set up the initial extension and implement the erd as seen here 
https://drive.google.com/a/freerunningtechnologies.com/file/d/0B-7iL6VFXiX0UTJfX0xROXdwWjQ/view?usp=sharing
> Implement erd

- spec/rails_helper.rb
> require pry in the test suite

- app/models/solidus_subscriptions/line_item.rb
- app/overrides/spree/line_items/subscription_line_items_association.rb
- app/overrides/spree/orders/subscription_line_items_association.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
- spec/overrides/spree/line_items/subscription_line_items_association_spec.rb
- spec/overrides/spree/orders/subscription_line_items_association_spec.rb
Establish the relationships between Spree::Orders, Spree::LineItems and SolidusSubscription::LineItems
> Line items have orders

- app/models/solidus_subscriptions/installment_detail.rb
- db/migrate/20160902220242_remove_state_from_solidus_susbscriptions_installment_details.rb
- db/migrate/20160902220604_add_successful_to_solidus_subscriptions_installment_details.rb
- db/migrate/20160902221218_add_message_to_solidus_subscriptions_installment_details.rb
- spec/models/solidus_subscriptions/installment_detail_spec.rb
Remove InstallmentDetail #state, Replace it with #success
Add InstallmentDetail#message
> Installment detail attributes

- app/models/solidus_subscriptions/installment_detail.rb
- spec/factories/installment_detail_factory.rb
- spec/models/solidus_subscriptions/installment_detail_spec.rb
Add a Factory for installment details 
Add a helper method #failed?, Which is the opposite of #success?
> Installment detail stuff

- app/models/solidus_subscriptions/installment.rb
- config/locales/en.yml
- spec/models/solidus_subscriptions/installment_spec.rb
Add a method to installments which knows how to mark the installment and failed due to lack of stock
> Installment out of stock

- .travis.yml
- Gemfile
- app/models/solidus_subscriptions/consolidated_installment.rb
- db/migrate/20160825202248_create_solidus_subscriptions_installments.rb
- db/migrate/20160825211202_create_solidus_subscriptions_installment_details.rb
- solidus_subscriptions.gemspec
- spec/controllers/orders/create_subscription_line_items_spec.rb
- spec/factories/subscription_factory.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
Add CI for all our testing needs. Tests the gem against all supported Rails 4 versions of solidus
> Add CI to the project

- Gemfile
For now because we havnt made sure this works on rails 5 (and solidus
2.0) this should be restricted to the 1.4 branch of solidus
> Fix gemfile

- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
When a variant is out of stock the shared examples for a completed
checkout no longer apply, however we still want to check that the order
was successful, just with 1 fewer line items
> Improve out of stock variant specs

- app/overrides/views/admin_subscribable_checkbox.rb
- app/views/spree/admin/variants/_subscribable_checkbox.html.erb
- lib/solidus_subscriptions.rb
- solidus_subscriptions.gemspec
> Add checkbox for marking variants as subscribable

- app/overrides/spree/users/have_many_subscriptions.rb
- spec/overrides/spree/users/have_many_subscriptions.rb
Spree::Users maintain a list of the subscriptions associated with them
https://www.pivotaltracker.com/story/show/129164287
> Spree.user_class#subscriptions

- docs/api/v1/orders.md
- docs/api/v1/subscription_line_items.md
Document the JSON API endpoints for creating and updating subscritpion line items
> Document the JSON API 

- app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
- config/routes.rb
- lib/solidus_subscriptions.rb
- lib/solidus_subscriptions/ability.rb
- lib/solidus_subscriptions/engine.rb
- spec/controllers/solidus_subscriptions/api/v1/line_items_controller_spec.rb
> Add destroy endpoint for subscription line items

- app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
- spec/controllers/solidus_subscriptions/api/v1/subscriptions_controller_spec.rb
- spec/rails_helper.rb
> Enforce 100% test coverage

- app/models/solidus_subscriptions/installment.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
The gem should be timezone aware
> Prefer Date.current over Date.today

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/payment_failed_dispatcher.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/payment_failed_dispatcher_spec.rb
Handle a failed payment on a subscription order
> Payment failure

- lib/solidus_subscriptions.rb
> Require all of solidus

- README.md
This is NOT a released extension yet, and probably doesn't work for most
people yet.
> Add scary warning mentioning the current state

- app/models/dispatcher.rb
- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/dispatcher.rb
- app/models/solidus_subscriptions/failure_dispatcher.rb
- app/models/solidus_subscriptions/out_of_stock_dispatcher.rb
- app/models/solidus_subscriptions/payment_failed_dispatcher.rb
- app/models/solidus_subscriptions/success_dispatcher.rb
- spec/models/solidus_subscriptions/dispatcher_spec.rb
- spec/models/solidus_subscriptions/out_of_stock_dispatcher_spec.rb
- spec/models/solidus_subscriptions/payment_failed_dispatcher_spec.rb
Move this functionality into a superclass to standardize the dispatcher
interface
> The dispatchers all share functionality

- app/controllers/spree/admin/subscriptions_controller.rb
- config/routes.rb
- spec/controllers/spree/admin/subscriptions_controller_spec.rb
This controller is responsible for admin actions related to
SolidusSubscriptions::Subcriptions
> Add Admin::SubscriptionsController

- lib/solidus_subscriptions/engine.rb
- lib/solidus_subscriptions/processor.rb
- lib/tasks/process_subscriptions.rake
A few issues I noticed running the processor on a default store
> Some processing fixups

- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/subscription.rb
- app/views/spree/admin/subscriptions/_subscription.html.erb
- app/views/spree/admin/subscriptions/index.html.erb
- config/locales/en.yml
- lib/solidus_subscriptions/testing_support/factories/installment_factory.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
Add an index area for managing subscriptions
> Subs index

- app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
- lib/solidus_subscriptions/ability.rb
- spec/controllers/solidus_subscriptions/api/v1/line_items_controller_spec.rb
- spec/lib/solidus_subscriptions/ability_spec.rb
Dont give default customers the manage ability, it opens too many doors.
Create a second set of abilities for admin users
> Fix abilities

- app/controllers/spree/admin/subscriptions_controller.rb
- app/models/solidus_subscriptions/subscription.rb
- app/views/spree/admin/subscriptions/index.html.erb
- spec/models/solidus_subscriptions/subscription_spec.rb
Allow the subscriptions index to be filtered by
- created date
- actionable date
- subscription state
- processing state
- user email
> Subs search

- app/overrides/views/admin_subscriptions_menu_link.rb
- app/views/spree/admin/shared/_subscription_tab.html.erb
- app/views/spree/admin/subscriptions/index.html.erb
- config/locales/en.yml
- lib/solidus_subscriptions/engine.rb
- spec/features/admin_link_spec.rb
- spec/rails_helper.rb
Jam this link into the admin sidebar
> Add a link to the subscriptions backend area

- app/models/solidus_subscriptions/consolidated_installment.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
Previously, The Out of stock dispatcher was initialized with an empty
array and the system would log that it had failed to process <blank>
installments due to lack of stock.
The Failure dispatcher would be initalized with a blank array if the
order was successfully placed.
Both of the se dispatchers should only be activated if there is an
actially installment to justify notifying someone of this event
> Only log failed installments

- db/migrate/20161014212649_allow_spree_line_item_id_to_be_null.rb
Not all subscriptions will have spree_line_items
> Allow the spree_line_item_id to be nil

- app/controllers/spree/admin/subscriptions_controller.rb
- app/decorators/spree/variant_pretty_name.rb
- app/views/spree/admin/shared/_no_objects_found.html.erb
- app/views/spree/admin/subscriptions/_form.html.erb
- app/views/spree/admin/subscriptions/index.html.erb
- app/views/spree/admin/subscriptions/new.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/spree/admin/subscriptions_controller_spec.rb
- spec/models/spree/variant_spec.rb
Create new subscriptions through the admin interface
> Admin interface for creating new subscriptions 

- app/views/spree/admin/subscriptions/edit.html.erb
- config/routes.rb
Somehow the route for updating subs was not implemented
> Actually update subscriptions from the admin

- .travis.yml
- Gemfile
- lib/solidus_subscriptions/config.rb
- solidus_subscriptions.gemspec
- spec/controllers/spree/admin/subscriptions_controller_spec.rb
- spec/lib/solidus_subscriptions/processor_spec.rb
> Spec against Solidus 2.0
