brendandeere/solidus_subscriptions

- app/models/solidus_subscriptions/subscription.rb
- lib/solidus_subscriptions.rb
- solidus_subscriptions.gemspec
- spec/models/solidus_subscriptions/subscription_spec.rb
The subscription state determines the behaviours around when it is
processed. Here is a brief description of the states and how they affect
the subscription.
[active] Default state when created. Subscription can be processed
[canceled] The user has ended their subscription. Subscription will not
be processed.
[pending_cancellation] The user has ended their subscription, but the
conditions for canceling the subscription have not been met. Subscription
will continue to be processed until the subscription is canceled and
the conditions are met.
[inactive] The number of installments has been fulfilled. The subscription
will no longer be processed
> Subscriptions state machine

- app/models/solidus_subscriptions/subscription.rb
- spec/factories/line_item_factory.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
Subscriptions know when the next time they should be processed will be. For now this will be  Current actionable date + interval.
There  may be more work to do here to synchronise multiple subscriptions for a user
> Next actionable date

- app/models/solidus_subscriptions/consolidated_installment.rb
- solidus_subscriptions.gemspec
- spec/factories/installment_factory.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
This class takes a collection of installments and populates a new
spree order with the correct contents based on the subscriptions associated
to the intallments. This is to group together subscriptions being
processed on the same day for a specific user
https://www.pivotaltracker.com/story/show/129392393
> Consolidated installment

- app/overrides/spree/controllers/orders/create_subscription_line_items.rb
- app/overrides/spree/controllers/orders/subscription_params.rb
- spec/controllers/orders/create_subscription_line_items_spec.rb
Create new subscription line items associated to the current order, when
a line item is added to the cart which includes subscription_line_item
params.
The Subscriptions::LineItem acts as a line item place holder for a
Subscription, indicating that it has been added to the order, but not
yet purchased
> Create Subscriptions::LineItems on #populate

- app/models/solidus_subscriptions/subscription_generator.rb
- app/overrides/spree/orders/finalize_creates_subscriptions.rb
- spec/factories/spree/line_item_factory.rb
- spec/factories/spree/order_factory.rb
- spec/models/solidus_subscriptions/subscription_generator_spec.rb
- spec/overrides/spree/orders/finalize_creates_subscrptions_spec.rb
Once an order is finalized its subscriptions line items should be converted
into active subscritptions. This hooks into Spree::Order#finalize! and
passes all subscription_line_items present on the order to the Subscription
generator which will build and persist the subscriptions
https://www.pivotaltracker.com/story/show/129386737
> Subscription generator

- app/models/solidus_subscriptions/line_item_builder.rb
- app/models/solidus_subscriptions/order_builder.rb
- spec/models/solidus_subscriptions/line_item_builder_spec.rb
- spec/models/solidus_subscriptions/order_builder_spec.rb
Add SubscribableSupplier
This class is responsible for taking a SubscriptionLineItem and building
it into a Spree::LineItem which can be added to an order
Provides two methods, one which always returns a new line item for the subscribable line item and a second which will add the line item to a given order, or increment the line item quanitity if it already exists on the order. 
https://www.pivotaltracker.com/story/show/129393347
> Subscribable LineItem and Order builder models 

- spec/factories/installment_factory.rb
- spec/factories/line_item_factory.rb
- spec/factories/subscription_factory.rb
Improve the factories 
- Remove an unneeded test value
- Actually create a subscribable object for line ites 
- Ensure subscriptions with line items have a "root order" which is completed. This is the order that initially created the subscription
> Updated factories

- spec/lib/solidus_subscriptions/config_spec.rb
Since the config spec changes global setting on a constant that isnt
reloaded between example, these specs alter the environment that all
other specs are running in.
It wasnt detected becuase no other specs use the default_gateway config
(yet).
Add some meta_data that will reset the default gateway value to the
initial value after running the spec.
This metadata is required on any spec that will use the default_gateway
config. Since reading this value will attempt to set a value if it can
find an appropriate gateway
> Fix Terrible Order dependent spec

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/subscription.rb
- spec/helpers/checkout_infrastructure.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/spec_helper.rb
A Consolidated installment can produce a Spree::Order with the correct
contents and move it entirely through the checkout process until it is
completed
> Create full orders

- app/models/solidus_subscriptions/order_builder.rb
- spec/models/solidus_subscriptions/order_builder_spec.rb
When this was changed from the supplier to the order builder, some docs
were not updated. Some of the behaviour was not consistent either.
- add_line_items returns the list of line_items present on the order
- Update docs to reflect this
> Update docs and methods for consistency

- solidus_subscriptions.gemspec
Some messages (for example installment processing messages) will be
displayed to the customer. Provide these as translations for easy
internationalization
> Add I18n for messages intended for display

- app/models/solidus_subscriptions/line_item_builder.rb
- app/models/solidus_subscriptions/unsubscribable_error.rb
- spec/models/solidus_subscriptions/line_item_builder_spec.rb
To declutter the line item builder and to have the error belong to the
SolidusSubscriptions namespace
> Move Unsubscribable error into its own class

- lib/solidus_subscriptions/config.rb
This option represents  the time between an installment failing to be processed and the system retrying to fulfil it
> Make reprocessing interview a configurable option?

- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/out_of_stock_dispatcher.rb
- config/locales/en.yml
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/out_of_stock_dispatcher_spec.rb
This service class is intented to provide callback behaviour to handle
the case where an installment cannot be processed due to lack of stock.
This PR depends on #26
> Out of stock dispatcher

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/line_item_builder.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/line_item_builder_spec.rb
If a particular line item is out of stock the consolidated order should
call the out of stock handler for the installment. This installment
should also be removed from the active installments the consolidated
installment is processing. This will avoid it having a completed order
associated to it which does not actually fulfill the failed installment
> Out of stock

- app/models/solidus_subscriptions/subscription.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
Add a scope to the Subscription model for finding all subscriptions that are
not canceled or inactive, and that have an actionable_date in the past.
> Scope for finding subscriptions ready for action

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/success_dispatcher.rb
- config/locales/en.yml
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/success_dispatcher_spec.rb
When a subscription order is successfully completed, the success
callback handler should be run. by default it calls the success method
on all relevant installments and then runs a notifier
> Success handler

- app/overrides/spree/controllers/orders/subscription_params.rb
- lib/solidus_subscriptions/config.rb
This is useful in the case where certain fields should not be allowed to
be modified by the user. This locks these attributes from being passed
in to the orders controller (or the api controller).
Ie if a store does not want to allow users to configure the number of
installments they will receive. Add this to an initializer:
```
SolidusSubscriptions::Config.subscription_line_item_attributes = [
:quantity,
:interval,
:subscribable_id
]
```
This configuration also easily allows the gem to be customized to track
more information on the subcriptions line items if someone wanted to do
that
> Configurable subscription line item params

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/failure_dispatcher.rb
- app/models/solidus_subscriptions/installment.rb
- config/locales/en.yml
- spec/models/solidus_subscriptions/failure_dispatcher_spec.rb
- spec/models/solidus_subscriptions/installment_spec.rb
In order to make sure that installments are always marked for
reprocessing, ensure that even if an error is raised any installments
not associated to a completed order are marked as failed so that they
will be reprocessed in the future
> Failure handler

- app/overrides/spree/controllers/orders/create_subscription_line_items.rb
- app/overrides/spree/controllers/orders/subscription_params.rb
- lib/solidus_subscriptions/config.rb
- spec/controllers/orders/create_subscription_line_items_spec.rb
The add to cart form nests all params under the order key. Update the
subscription line items to respect that.
> Update subscription line item params

- app/models/solidus_subscriptions/line_item.rb
- app/overrides/spree/controllers/orders/subscription_params.rb
- app/overrides/spree/line_items/subscription_line_items_association.rb
- solidus_subscriptions.gemspec
- spec/controllers/spree/api/orders_controller_spec.rb
- spec/overrides/spree/line_items/subscription_line_items_association_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
The api orders controller allows nested attributes for subscritpion line
ites to be posted to it when adding line items to the order. This allows
subscriptions line items to be created through the api.
JSON param example
```js
{
order_token: '1234'
order: {
line_items_attributes: [{
// line item attributes
subscription_line_items_attributes: [{
quantity: 1,          // How many to include in the
subscription orders
max_installments: 12, // How many times to process the
subscriptions
interval: 2592000,    // frequency of subscription orders (in
seconds)
subscribable_id: 1234 // What item to include in the
subscription order
}]
}]
}
}
```
> Api orders controller creates subscription line items

- README.md
- app/models/solidus_subscriptions/line_item.rb
- app/models/solidus_subscriptions/subscription.rb
- db/migrate/20160922164101_add_interval_length_and_units_to_subscription_line_items.rb
- lib/solidus_subscriptions/config.rb
- lib/solidus_subscriptions/testing_support/factories/line_item_factory.rb
- solidus_subscriptions.gemspec
- spec/controllers/orders/create_subscription_line_items_spec.rb
- spec/controllers/spree/api/orders_controller_spec.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
- spec/rails_helper.rb
Forcing consumers of the API to calculate and provide the interval in
seconds is messy and unnecessary. Instead, we can store the interval as
length and units, and do the math ourselves. This makes the API much
easier to use and understand.
> Human-friendly intervals

- app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
- lib/solidus_subscriptions.rb
- lib/solidus_subscriptions/ability.rb
- lib/solidus_subscriptions/engine.rb
- spec/controllers/solidus_subscriptions/api/v1/line_items_controller_spec.rb
This adds a CanCan class for modelling our permissions. This then
modifies the LineItemsController to use the new CanCan abilities instead
of manually checking.
> Add CanCan abilities class

- app/overrides/spree/controllers/orders/create_subscription_line_items.rb
- app/overrides/spree/controllers/orders/subscription_params.rb
- spec/controllers/orders/create_subscription_line_items_spec.rb
Restrict the after_action which adds subscription line items to the cart
to the :populate action of the Spree::OrdersController.
Only run this action if there are the correct parameters for it
Cart params are not nested under order
> Fix after action to create subs line items

- app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
`:subscription_line_item` does not match the controller's model name,
which is inconsistent and causes problems for people using things like
Backbone model serialisation.
> Use canonical model name for params namespace

- app/decorators/spree/line_items/subscription_line_items_association.rb
If a line item is destroyed, the associated subscription_line_items
should also get blown away. No subscription line item is permitted to
exist independently of a line item. The subscription needed to be
"ordered" somehow
> Line items dependent destroy subs line items

- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/line_item.rb
- app/models/solidus_subscriptions/subscription.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
There are a few values needed in the cart which have to be calculated,
given that subscriptions aren't created until after an order is
finalized.
Allow the subscription line item to calculate its: 
- name
- price
- next_actionable_date
> Subs line item name

- app/models/solidus_subscriptions/line_item.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
Expose the dummy line item which is a representation of a line item
which would be added to a subscription order when the subscription was
processed.
It can be used to render the subcription_line_item in the cart. The
object is a frozen, unpersisted instance and cannot be saved
> SubscriptionLineItem#dummy_line_item

- app/models/solidus_subscriptions/subscription_generator.rb
- spec/overrides/spree/orders/finalize_creates_subscrptions_spec.rb
When the order is finalized it should create a fully actionable
subscription. This means it includes an actionable date
> Actually set the actionable date

- README.md
- app/models/solidus_subscriptions/line_item.rb
- docs/api/v1/subscriptions.md
- lib/solidus_subscriptions/testing_support/factories/line_item_factory.rb
- spec/controllers/orders/create_subscription_line_items_spec.rb
- spec/controllers/spree/api/orders_controller_spec.rb
- spec/controllers/spree/api/users_controller_spec.rb
This makes it easier for people on the frontend to pluralize, instead of
conditionally singularizing. Since this is an enum, this change makes
virtually no difference to us.
> Change interval enum units to singular

- app/jobs/solidus_subscriptions/process_installments_job.rb
- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/subscription.rb
- lib/solidus_subscriptions/config.rb
- lib/solidus_subscriptions/engine.rb
- lib/solidus_subscriptions/processor.rb
- lib/solidus_subscriptions/testing_support/factories/installment_detail_factory.rb
- lib/solidus_subscriptions/testing_support/factories/installment_factory.rb
- lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
- lib/tasks/process_subscriptions.rake
- spec/jobs/solidus_subscriptions/process_installments_job_spec.rb
- spec/lib/solidus_subscriptions/processor_spec.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
Actionable subscriptions and installments can now be processed with the
rake task:
`bundle exec rake solidus_subscriptions:process`
> Rake task and job

- app/models/solidus_subscriptions/subscription_promotion_rule.rb
- config/locales/en.yml
- lib/solidus_subscriptions/engine.rb
- spec/models/solidus_subscriptions/subscription_promotion_rule_spec.rb
Add the custom promotion rule to the list of solidus promotion rules.
add some translations and an empty template so that the admin can render
the promotion rule properly
This doesnt need an image... but Im stoked about it
> Promo rule

- app/decorators/spree/controllers/orders/create_subscription_line_items.rb
Some promotions act on subscription_line_items, make sure to rerun the
promotion handler after they are created
> Rerun promotion handler

- app/models/solidus_subscriptions/subscription.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
If the subscription is not active, then there is no next actionable
date, so this should be set to nil. This also relieves the need for the
`unset_actionable_date` method.
> Make next_actionable_date nil when not active

- app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb
- app/models/solidus_subscriptions/subscription.rb
- config/routes.rb
- docs/api/v1/subscriptions.md
- spec/controllers/solidus_subscriptions/api/v1/subscriptions_controller_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
- spec/requests/solidus_subscriptions/api/v1/subscriptions_spec.rb
Allows the caller to defer their subscription installment for another
month. This just bumps the actionable_date so it won't be processed
during the next rake task invocation.
> Add #skip to subscriptions controller

- app/models/solidus_subscriptions/line_item.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
If a subscription's line_item interval changes, we need to update the
actionable_date on the subscription in case the new interval means we
need to process the subscription immediately.
For example, if you have an interval of 3 months, and you change it to 1
month 2 months in, we should update the subscription to be actionable
immediately, as the new interval has passed since the last installment.
> Update actionable_date when interval changes

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/subscription_order_promotion_rule.rb
- config/locales/en.yml
- lib/solidus_subscriptions/engine.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/subscription_order_promotion_rule_spec.rb
- spec/rails_helper.rb
Add a promotion rule that targets orders creates as the result of processing a
subscription.
When creating new orders, run the order adjuster to take any applicable
promotions into account
> Subscription order promo rule

- app/models/solidus_subscriptions/subscription_line_item_builder.rb
If we dont recalculate the order totals after applying promotions to
account for subscriptions, the total values will be wrong
> Reload order totals after applying promotions

- app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
- lib/solidus_subscriptions/ability.rb
- spec/controllers/solidus_subscriptions/api/v1/line_items_controller_spec.rb
Previously the ability assumed that all subscription_line_items would
have a user through the order. This however is not the case since the
user login is not enforced until after the user tries to transition out
of the cart step.
Allow guests to edit their line items if the line item matches the
current checkout_id (order guest token )
> Allow guests to edit their subss line items

- lib/solidus_subscriptions/ability.rb
The hash conditions are more flexible and allow the permission set to be
used in more circumstances
https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities%3A-Best-Practice
> Prefer hash conditions over blocks

- app/models/solidus_subscriptions/subscription.rb
- docs/configuration.md
- lib/solidus_subscriptions/config.rb
- lib/solidus_subscriptions/processor.rb
- lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
- spec/controllers/solidus_subscriptions/api/v1/subscriptions_controller_spec.rb
- spec/lib/solidus_subscriptions/processor_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
- spec/requests/solidus_subscriptions/api/v1/subscriptions_spec.rb
Only allow subscription cancellation if the minimum notice has not yet
past. If it has the subscription will be transitioned to the pending
cancellation state
> Config minimum cancellation notice

- app/models/solidus_subscriptions/consolidated_installment.rb
- docs/configuration.md
- lib/solidus_subscriptions/config.rb
The dispatcher classes are intended to be hooks into the proccing
algorithm.
Allowing these classes to be plugged into the gem gives users more
flexibility as to how their app handles certain events during handling.
These events are:
Success - All installments were processed and fulfilled by a single
order
Failure - No installments were fulfilled due to a generic error
OutOfStock - Some installments were not fulfilled because there was
insufficient stock to do so
PaymentFailed - No installments were fulfilled due do a payment error.
When plugging in a new class it is highly recommented to subclass from
the dispatcher you are replacing, and call super if you override the
#dipatch method. This ensures the internal models handled correctly.
Custom behaviour should be added in addition to the …
> Make the dispatchers pluggable

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/user_mismatch_error.rb
- spec/jobs/solidus_subscriptions/process_installments_job_spec.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
Consolidated installments make the assumption that all installments
passed in share the same user. This is a critical assumption that I feel
merrits a validation.
An error will be raised with the ids of the installments which were
attempted to be consolidated.
> Only process consolidated installments for the same user

- app/models/solidus_subscriptions/line_item.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
Subscriptions created through the backed do not require a purchasing
order (line item).
> Remove spree_line_item validation

- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
This is a sanity check spec to make sure store credits are applied to
subscription orders during the checkout.
This is solidus default behaviour, and while it may not be the desired
behaviour for every subscription implementation. Changeing this default
behaviour could be intensive. I am opting to wait for this to be a
feature requeset before implementing the ability to blacklist store
credit on subs orders
> Spec store credit subs orders

- README.md
- apidoc/configuration.md
- lib/solidus_subscriptions/config.rb
- spec/helpers/checkout_infrastructure.rb
- spec/lib/solidus_subscriptions/config_spec.rb
So Ive been running into the problem of the gateway being evaluated too
early (before the db is created) having it be explicitely set in an
initializer.
Im now specifying the default gateway in a block so that it will not be
evaluated until it is actually needed
> Initialize the gateway with a block

- app/decorators/spree/orders/after_create.rb
- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/dispatcher.rb
- app/models/solidus_subscriptions/failure_dispatcher.rb
- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/installment_detail.rb
- app/models/solidus_subscriptions/payment_failed_dispatcher.rb
- app/models/solidus_subscriptions/subscription.rb
- app/models/solidus_subscriptions/subscription_order_promotion_rule.rb
- app/models/solidus_subscriptions/success_dispatcher.rb
- db/migrate/20161017155749_add_order_id_to_solidus_subscriptions_installment_details.rb
- db/migrate/20161017175509_remove_order_id_from_solidus_subscriptions_installments.rb
- db/migrate/20161017201944_add_subscription_order_to_spree_orders.rb
- lib/solidus_subscriptions/config.rb
- lib/solidus_subscriptions/testing_support/factories/installment_factory.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/failure_dispatcher_spec.rb
- spec/models/solidus_subscriptions/installment_detail_spec.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/payment_failed_dispatcher_spec.rb
- spec/models/solidus_subscriptions/subscription_order_promotion_rule_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
It was pointed out that if there is any error raised after the payment
is authorized, the transaction would roll back and we would have no
record of the authorization.
All installment details now have an associated order which is the order
resulting from that attempt at processing an installment. It can be
completed or not
The order for each processing attempt can now be inspected to see what went wrong. Installments now no longer track which spree order has fulfilled them directly
> Checkout rework

- app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
This could affect promotions if they are targeting line items with
associated subscription line items
> Update order on subscription line item removal

- apidoc/configuration.md
- lib/solidus_subscriptions/config.rb
- lib/solidus_subscriptions/permitted_attributes.rb
Allow the Subscription permitted attributes to be configurable from an initializer. 
By default, Subscriptions now accept the actionable date as a permitted attribute
> make_subs_permitted_attriubtes_configurable

- Rakefile
- app/models/solidus_subscriptions/order_builder.rb
- spec/models/solidus_subscriptions/order_builder_spec.rb
Not really sure how this was correct before.
When the line item already existed on an order, the builder would
increment the quantity of the line item without saving it. in the specs,
a different instance of the line item would be tested resulting in the
change in quantity not being apparent to the spec
> Fix spec failures

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/order_builder.rb
- app/models/solidus_subscriptions/subscription.rb
- app/models/solidus_subscriptions/subscription_generator.rb
- db/migrate/20161221155142_add_store_to_solidus_subscriptions_subscriptions.rb
- lib/solidus_subscriptions/testing_support/factories/spree_modification_factory.rb
- lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
- spec/lib/solidus_subscriptions/processor_spec.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/subscription_generator_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
The root order was a concept used as a fallback for shipping addresses and payment methods when creating subscription orders.
It relied on a 1 - 1 relationship between the subscription and a subscription line item. 
This is something we have decided to change in order to support subscriptions with multiple subscription line items. 
Given a subscription must have a user  (and in future we should validate that that user has a ship address and payment method). We will always grab the ship address and payment method from the user.
We will store the spree_store on the subscription when it is created. 
Existing stores will want to add this migration after dropping the `root_order` relationship
```ruby
class PopulateSubscriptionStoreIds < ActiveRecord::Migration
def change
q = <<-SQL
UPDATE …
```
> Remove root order

- app/models/solidus_subscriptions/line_item.rb
This is much safer than the array syntax. the db indexes are explicitely
set on the model and are less likely to be accidentally changed.
These indexes are in the same order as the array was defined, no app
should notice a difference unless they have changed the order of this
array
> Use hash syntax for enums

- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/line_item.rb
- app/models/solidus_subscriptions/line_item_builder.rb
- app/models/solidus_subscriptions/subscription.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/line_item_builder_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
In preparation of moving to subscriptions supporting multiple
subscription line items. The line item builder needs to be updated to
accept a collection of line items.
> Line item builder accepts a collection of line items

- app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb
- app/controllers/spree/admin/subscriptions_controller.rb
- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/line_item.rb
- app/models/solidus_subscriptions/line_item_builder.rb
- app/models/solidus_subscriptions/subscription.rb
- app/models/solidus_subscriptions/subscription_generator.rb
- lib/solidus_subscriptions/permitted_attributes.rb
- lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
- spec/controllers/solidus_subscriptions/api/v1/subscriptions_controller_spec.rb
- spec/controllers/spree/api/users_controller_spec.rb
- spec/lib/solidus_subscriptions/processor_spec.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/line_item_builder_spec.rb
- spec/models/solidus_subscriptions/subscription_generator_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
- spec/overrides/spree/orders/finalize_creates_subscrptions_spec.rb
We are going to support multiple items per subscription. This commit
changes the subscription -> subscription_line_item relationship from a
has_one to a has_many.
Most of the changes here are simply pluralization changes. Somethat are
not:
Api params now take:
`line_items_attributes instead` of `line_item_attributes` for nested params
to a subscription
`subscription_line_items_attributes` instead of
`subscription_line_item_attributes`
Only the interval and max installemnts of the first subscription_line_item is considered
> Subscriptions support multiple subscription_line_items

- app/jobs/solidus_subscriptions/process_installments_job.rb
- lib/solidus_subscriptions/processor.rb
The processor looks up a number of users, subscriptions and installments
and passes them off to an Active Job.
Before we were doing a number of n+1 queries and relying on the rails
global id when passing objects to the consolidated installments.
This commit removes the greedy queries and passes a list of ids to the
active job object so that all affected objects can be looked up in a
single query
Local speed test processing 100 subscriptions all belonging to a single user (Postgres):
before: 7404.390109999999 milliseconds
after: 6939.091705 milliseconds
> Remove some n+1 queries from processing

- apidoc/configuration.md
- app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb
- app/jobs/solidus_subscriptions/process_installments_job.rb
- app/models/solidus_subscriptions/consolidated_installment.rb
- app/models/solidus_subscriptions/line_item.rb
- app/models/solidus_subscriptions/subscription.rb
- app/models/solidus_subscriptions/subscription_generator.rb
- db/migrate/20161223152905_add_address_id_to_solidus_subscriptions_subscriptions.rb
- lib/solidus_subscriptions/config.rb
- lib/solidus_subscriptions/processor.rb
- lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
- spec/controllers/solidus_subscriptions/api/v1/subscriptions_controller_spec.rb
- spec/lib/solidus_subscriptions/processor_spec.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/line_item_spec.rb
- spec/models/solidus_subscriptions/subscription_generator_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
In order to allow for users to manage subscriptions for other people
(family members etc) we are going to store a shipping address directly
on the subscription. This way a user can ship different subscriptions to
different addresses
The default shipping address for a subscription is the shipping address
of the order that purchased it.
Subscriptions are grouped together and processed by user and and by shipping address.
```
A user has 3 subscriptions (A, B and C). A and B have the same shipping
address, but C will be shipped to a different location.
The processor will group and process installments for A and B together
and they will be fulfilled by the same order.
A second order will be created to fulfill C.
```
The api allows subscription shipping addresses to be updated as a nested …
> Subs have addresses

- app/models/solidus_subscriptions/installment.rb
- app/models/solidus_subscriptions/subscription.rb
- db/migrate/20170111224458_change_subscription_actionable_date_to_datetime.rb
- db/migrate/20170111232801_change_inteval_actionable_date_to_datetime.rb
- lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
- spec/models/solidus_subscriptions/consolidated_installment_spec.rb
- spec/models/solidus_subscriptions/installment_spec.rb
- spec/models/solidus_subscriptions/subscription_spec.rb
- spec/overrides/spree/orders/finalize_creates_subscrptions_spec.rb
- spec/requests/solidus_subscriptions/api/v1/subscriptions_spec.rb
Increase actionable date granularity by tracking it as a date time
> Change dates to date times
